name: ESLint
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint
  report:
    name: Teams integratie
    needs: [build]
    if: ${{always()}}
    runs-on: ubuntu-latest
    steps:
      - name: teams-webhook
        uses: FreEZer00/teams-webhook-action@v1.4.2
        with:
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
